### ISSUE TITLE
Pr2: en `agregarAlFinal` no estás usando recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#10]
Si bien no está mal utilizar subtareas, esta es una práctica de recursión estructural, y la idea es que las puedan hacer con recursión estructural, en aquellos casos que se pueda (como este).
Si la vas a hacer con subtareas, el primer caso es innecesario (porque está cubierto por el segundo).

**Comment by Fernando-Montero** [comment]
modificado

**Comment by fidel-ml** [comment]
Sigue igual

**Comment by Fernando-Montero** [comment]
modificado para aplicar la recursion estructural
