### ISSUE TITLE
Pr2: `agregar` tiene dos defectos

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#11]
El primero es que estás mirando ambos argumentos, y esto en general no es correcto: elegí uno y quedate con ese.
El segundo es que al elegir el 2do argumento la función es mucho más ineficiente de lo que podría ser. Es mucho más adecuado hacer recursión en el primero...

**Comment by Fernando-Montero** [comment]
arreglado
