### ISSUE TITLE
Pr2: la función `asignadosPorProyecto` recorre la empresa muchas veces

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#19]
Si usás recursión estructural en lugar de 400 subtareas, sale con mucho menos esfuerzo...

**Comment by Fernando-Montero** [comment]
actualizado

**Comment by fidel-ml** [comment]
Mientras sigas utilizando `cantRolEnProyecto` vas a estar recorriendo más veces de la cuenta, no importa en cuántas subtareas dividas. Tenés que usar RECURSIÓN ESTRUCTURAL sin duplicar los proyectos en el 1er paso...
Además, ahora `cantRolEnProyecto` tiene un caso innecesario, pues está cubierto por el 2do caso. NO debés hacer doble PM a menos que el problema lo requiera. No se trata de buscar detectar 250mil casos, sino de entender la ESTRUCTURA del problema.

**Comment by Fernando-Montero** [comment]
actualizada a base de la resolución vista en clase
