### ISSUE TITLE
Pr2: `cantQueTrabajanEn` es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#20]
Estás mirando todas las personas, y no solamente los desarrolladores...

**Comment by Fernando-Montero** [comment]
me dí cuenta que me olvidé del Magement en general, renombré varias funciones que solo hacian referencia a Deleloper 
actualizado

**Comment by fidel-ml** [comment]
Ahora, debido a que superponés ser developer con ser senior en el mismo control, estás contando menos de la cuenta (no contás ni managers, ni developers junior...)

**Comment by Fernando-Montero** [comment]
entendí mal la primera corrección, pensé que solo tenía que ver a todos los desarrolladores  pero asumo que tu comentario hace referencia al nombre de las funciones(todas relacionadas con desarrollador) , ahora cuenta a todas las personas que participen de un proyecto sin importar rango o si es manager/developer

**Comment by fidel-ml** [comment]
Parece estar mejor.
