### ISSUE TITLE
Pr2: `sinProyectosRepetidos` no usa subtareas...

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#22]
Y de esta forma realiza dos veces el llamado recursivo. Lo vimos en clase...

**Comment by Fernando-Montero** [comment]
actualizada

**Comment by fidel-ml** [comment]
Seguís teniendo un `sinRepetidos` con problemas. Ahora mirás la pertenencia de `x` a una lista más larga de lo necesaria... ¿Lo pensaste por RECURSIÓN ESTRUCTURAL y utilizando subtareas, tal cual lo vimos en clase?

**Comment by Fernando-Montero** [comment]
actualziado, ahora se pregunta sobre la recursión

**Comment by fidel-ml** [comment]
No querés QUITAR el proyecto si pertenece, sino AGREGARLO si no pertenece... :(

**Comment by Fernando-Montero** [comment]
me habia olvidado de conservar el elemento que estaba comparando

**Comment by fidel-ml** [comment]
Lo que estás haciendo es muy poco claro, y eficaz. Básicamente, estás recorriendo para sacar lo que ya pusiste, y volviéndolo a poner inmediatamente. Funciona, pero no es la manera que vimos en clase, y que deberías haber comprendido...
