### ISSUE TITLE
Pr3: `ponerN` no está hecha por recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#25]
¿Para qué mirás tantos casos? ¿Y por qué hacés esos manejos raros?
Sale MUCHO más fácil si usás la recursión estructural adecuada...

Recordá lo que dijimos ayer en clase: SIEMPRE deben primero darle una oportunidad a la recursión estructural ANTES de tratar de pensar 27 casos.

**Comment by Fernando-Montero** [comment]
corregido
