### ISSUE TITLE
Hay "miedo al booleano" en la función or

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#3]
En la función `oBien` estás haciendo una versión con pattern matching del "miedo al booleano".
Básicamente, preguntás si algo es `True` para devolver `True` y cuando no es `True` devolvés `False`. Está escondida debido al uso de guiones bajos sin pensar demasiado... :-D
Básicamente, es como si tuvieses `if b==True then True else False`, que es exactamente lo mismo que `b`.

**Comment by Fernando-Montero** [comment]
actualizado

**Comment by fidel-ml** [comment]
No cierres los issues...
