### ISSUE TITLE
Pr2: `conjugacion` no tiene el nombre pedido

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#7]
Debería ser `conjuncion`

**Comment by Fernando-Montero** [comment]
renombrado

**Comment by Fernando-Montero** [comment]
me fijé desde github y se ve actualizado 

![image](https://user-images.githubusercontent.com/102827038/164763555-6715e769-6c75-40f2-8170-958c510adcb2.png)
