### ISSUE TITLE
Pr 2: En `aplanar`, es feliz usar nombre de listas para las listas

### ISSUE THREAD

**Issue by fidel-ml** [Fernando-Montero/EstrD22s1#8]
Si un argumento tiene tipo `[a]` entonces es feliz llamarlo `xs` y no `x` (vendría de muchaS `x`). Esto permite identificar más fácilmente de qué va la función, sin necesidad de estar todo el tiempo haciendo saltos mentales.
Consecuentemente, si un argumento tiene tipo `[[a]]` lo llamamos `xss` (o sea, muchaS `xs`).

**Comment by Fernando-Montero** [comment]
actualizado

**Comment by fidel-ml** [comment]
Lo sigo viendo igual

**Comment by Fernando-Montero** [comment]
error mio, renombré los valores de otra función , arreglado
